// <internal keycode>: [<display label>, <optional short label>
export default {
    KC_BOOTLOADER: ['Bootloader', 'Btldr'],
    KC_RESET: ['Reset'],
    KC_NONE: ['None'],
    KC_TRANSPARENT: ['Transparent', 'Trns'],
    KC_A: ['A'],
    KC_B: ['B'],
    KC_C: ['C'],
    KC_D: ['D'],
    KC_E: ['E'],
    KC_F: ['F'],
    KC_G: ['G'],
    KC_H: ['H'],
    KC_I: ['I'],
    KC_J: ['J'],
    KC_K: ['K'],
    KC_L: ['L'],
    KC_M: ['M'],
    KC_N: ['N'],
    KC_O: ['O'],
    KC_P: ['P'],
    KC_Q: ['Q'],
    KC_R: ['R'],
    KC_S: ['S'],
    KC_T: ['T'],
    KC_U: ['U'],
    KC_V: ['V'],
    KC_W: ['W'],
    KC_X: ['X'],
    KC_Y: ['Y'],
    KC_Z: ['Z'],
    KC_1: ['1'],
    KC_2: ['2'],
    KC_3: ['3'],
    KC_4: ['4'],
    KC_5: ['5'],
    KC_6: ['6'],
    KC_7: ['7'],
    KC_8: ['8'],
    KC_9: ['9'],
    KC_0: ['0'],
    KC_ENTER: ['Enter'],
    KC_ESCAPE: ['Esc'],
    KC_BACKSPACE: ['Backspace', 'Bkspc'],
    KC_TAB: ['Tab'],
    KC_SPACEBAR: ['Space'],
    KC_MINUS: ['-'],
    KC_EQUAL: ['+'],
    KC_LEFT_BRACKET: ['['],
    KC_RIGHT_BRACKET: [']'],
    KC_BACK_SLASH: ['\\'],
    KC_ISO_HASH: ['ISO #'],
    KC_SEMICOLON: [';'],
    KC_APOSTROPHE: ['\''],
    KC_GRAVE: ['`'],
    KC_COMMA: [','],
    KC_PERIOD: ['.'],
    KC_FORWARD_SLASH: ['/'],
    KC_CAPS_LOCK: ['Caps Lock'],
    KC_F1: ['F1'],
    KC_F2: ['F2'],
    KC_F3: ['F3'],
    KC_F4: ['F4'],
    KC_F5: ['F5'],
    KC_F6: ['F6'],
    KC_F7: ['F7'],
    KC_F8: ['F8'],
    KC_F9: ['F9'],
    KC_F10: ['F10'],
    KC_F11: ['F11'],
    KC_F12: ['F12'],
    KC_PRINT_SCREEN: ['Print Screen'],
    KC_SCROLL_LOCK: ['Scroll Lock '],
    KC_PAUSE: ['Pause'],
    KC_INSERT: ['Insert'],
    KC_HOME: ['Home'],
    KC_PAGE_UP: ['Page Up'],
    KC_DELETE: ['Delete'],
    KC_END: ['End'],
    KC_PAGE_DOWN: ['Page Down'],
    KC_RIGHT_ARROW: ['Right'],
    KC_LEFT_ARROW: ['Left'],
    KC_DOWN_ARROW: ['Down'],
    KC_UP_ARROW: ['Up'],
    KC_NUM_LOCK: ['Num Lock'],
    KC_KP_FORWARD_SLASH: ['Keypad /', 'KP/'],
    KC_KP_ASTERISK: ['Keypad *', 'KP*'],
    KC_KP_MINUS: ['Keypad -', 'KP-'],
    KC_KP_PLUS: ['Keypad +', 'KP+'],
    KC_KP_ENTER: ['Keypad Enter', 'KPEnter'],
    KC_KP_1: ['Keypad 1', 'KP1'],
    KC_KP_2: ['Keypad 2', 'KP2'],
    KC_KP_3: ['Keypad 3', 'KP3'],
    KC_KP_4: ['Keypad 4', 'KP4'],
    KC_KP_5: ['Keypad 5', 'KP5'],
    KC_KP_6: ['Keypad 6', 'KP6'],
    KC_KP_7: ['Keypad 7', 'KP7'],
    KC_KP_8: ['Keypad 8', 'KP8'],
    KC_KP_9: ['Keypad 9', 'KP9'],
    KC_KP_0: ['Keypad 0', 'KP0'],
    KC_KP_PERIOD: ['Keypad .', 'KP.'],
    KC_ISO_BACK_SLASH: ['ISO \\'],
    KC_APPLICATION: ['App'],
    KC_KP_EQUAL: ['Keypad =', 'KP='],
    KC_F13: ['F13'],
    KC_F14: ['F14'],
    KC_F15: ['F15'],
    KC_F16: ['F16'],
    KC_F17: ['F17'],
    KC_F18: ['F18'],
    KC_F19: ['F19'],
    KC_F20: ['F20'],
    KC_F21: ['F21'],
    KC_F22: ['F22'],
    KC_F23: ['F23'],
    KC_F24: ['F24'],
    KC_HELP: ['Help'],
    KC_MENU: ['Menu'],
    KC_UNDO: ['Undo'],
    KC_CUT: ['Cut'],
    KC_COPY: ['Copy'],
    KC_PASTE: ['Paste'],
    KC_FIND: ['Find'],
    KC_MUTE: ['Mute'],
    KC_VOLUME_UP: ['Volume Up'],
    KC_VOLUME_DOWN: ['Volume Down'],
    KC_LOCKING_CAPS_LOCK: ['Locking Caps Lock', 'Locking Caps'],
    KC_LOCKING_NUM_LOCK: ['Locking Num Lock', 'Locking Num'],
    KC_LOCKING_SCROLL_LOCK: ['Locking Scroll Lock', 'Locking Scroll'],
    KC_KP_COMMA: ['Keypad ,', 'KP,'],
    KC_INTERNATIONAL_1: ['International 1', 'Int1'],
    KC_INTERNATIONAL_2: ['International 2', 'Int2'],
    KC_INTERNATIONAL_3: ['International 3', 'Int3'],
    KC_INTERNATIONAL_4: ['International 4', 'Int4'],
    KC_INTERNATIONAL_5: ['International 5', 'Int5'],
    KC_INTERNATIONAL_6: ['International 6', 'Int6'],
    KC_INTERNATIONAL_7: ['International 7', 'Int7'],
    KC_INTERNATIONAL_8: ['International 8', 'Int8'],
    KC_INTERNATIONAL_9: ['International 9', 'Int9'],
    KC_LANG_1: ['Language 1', 'Lang1'],
    KC_LANG_2: ['Language 2', 'Lang2'],
    KC_LANG_3: ['Language 3', 'Lang3'],
    KC_LANG_4: ['Language 4', 'Lang4'],
    KC_LANG_5: ['Language 5', 'Lang5'],
    KC_LANG_6: ['Language 6', 'Lang6'],
    KC_LANG_7: ['Language 7', 'Lang7'],
    KC_LANG_8: ['Language 8', 'Lang8'],
    KC_LANG_9: ['Language 9', 'Lang 9'],
    KC_RETURN: ['Return'],
    KC_KP_00: ['Keypad 00', 'KP00'],
    KC_KP_000: ['Keypad 000', 'KP000'],
    KC_LEFT_CONTROL: ['Left Control', 'LCtrl'],
    KC_LEFT_SHIFT: ['Left Shift', 'LShft'],
    KC_LEFT_ALT: ['Left Alt', 'LAlt'],
    KC_LEFT_GUI: ['Left GUI', 'LGUI'],
    KC_RIGHT_CONTROL: ['Right Control', 'RCtrl'],
    KC_RIGHT_SHIFT: ['Right Shift', 'RShft'],
    KC_RIGHT_ALT: ['Right Alt', 'RAlt'],
    KC_RIGHT_GUI: ['Right GUI', 'RGUI'],
    KC_MOUSE_UP: ['Mouse Up'],
    KC_MOUSE_DOWN: ['Mouse Down'],
    KC_MOUSE_LEFT: ['Mouse Left'],
    KC_MOUSE_RIGHT: ['Mouse Right'],
    KC_MOUSE_WH_UP: ['Mouse Wheel Up', 'Wheel Up'],
    KC_MOUSE_WH_DOWN: ['Mouse Wheel Down', 'Wheel Down'],
    KC_MOUSE_WH_LEFT: ['Mouse Wheel Left', 'Wheel Left'],
    KC_MOUSE_WH_RIGHT: ['Mouse Wheel Right', 'Wheel Right'],
    KC_MOUSE_BTN1: ['Mouse Button 1', 'Mouse1'],
    KC_MOUSE_BTN2: ['Mouse Button 2', 'Mouse2'],
    KC_MOUSE_BTN3: ['Mouse Button 3', 'Mouse3'],
    KC_MOUSE_BTN4: ['Mouse Button 4', 'Mouse4'],
    KC_MOUSE_BTN5: ['Mouse Button 5', 'Mouse5'],
    KC_MOUSE_BTN6: ['Mouse Button 6', 'Mouse6'],
    KC_MOUSE_BTN7: ['Mouse Button 7', 'Mouse7'],
    KC_MOUSE_BTN8: ['Mouse Button 8', 'Mouse8'],
    KC_SYSTEM_POWER: ['System Power'],
    KC_SYSTEM_SLEEP: ['System Sleep'],
    KC_SYSTEM_WAKE: ['System Wake'],
    KC_AUDIO_MUTE: ['Audio Mute'],
    KC_AUDIO_VOL_UP: ['Audio Volume Up', 'Audio VUp'],
    KC_AUDIO_VOL_DOWN: ['Audio Volume Down', 'Audio VDown'],
    KC_MEDIA_NEXT_TRACK: ['Media Next Track', 'Media ⏭'],
    KC_MEDIA_PREV_TRACK: ['Media Previous Track', 'Media ⏮'],
    KC_MEDIA_FAST_FORWARD: ['Media Fast Forward', 'Media ⏩'],
    KC_MEDIA_REWIND: ['Media Rewind', 'Media ⏪'],
    KC_MEDIA_STOP: ['Media Stop', 'Media ⏹'],
    KC_MEDIA_PLAY_PAUSE: ['Media Play/Pause', 'Media ⏯'],
    KC_MEDIA_EJECT: ['Media ⏏'],
    KC_MEDIA_SELECT: ['Media Select'],
    KC_MAIL: ['Mail'],
    KC_CALCULATOR: ['Calculator', 'Calc'],
    KC_MY_COMPUTER: ['My Computer'],
    KC_WWW_SEARCH: ['WWW Search'],
    KC_WWW_HOME: ['WWW Home'],
    KC_WWW_BACK: ['WWW Back'],
    KC_WWW_FORWARD: ['WWW Forward'],
    KC_WWW_STOP: ['WWW Stop'],
    KC_WWW_REFRESH: ['WWW Refresh'],
    KC_WWW_FAVORITES: ['WWW Favourites', 'WWW Favourite'],
}